Repository TeamSobokSobok/Sobok-iOS, pull requests merged in 2022-07, with the labels that each got.

#215 [#214] NoticeCollectionView 레거시 코드 제거
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Cells/FriendRequestCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Cells/PillRequestCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/ViewControllers/NoticeViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/NoticeListView.swift
Labels: 🤖 [Fix], 🍀 승찬

#217 [#219] SwiftLint Error 수정
  SobokSobok/SobokSobok/Application/SceneDelegate.swift
  SobokSobok/SobokSobok/Common/Extension/String+Extension.swift
  SobokSobok/SobokSobok/Common/Extension/UIAlertController+Extension.swift
  SobokSobok/SobokSobok/Common/Extension/UICollectionView + Extension.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Account/SaveNicknameModel.swift
  SobokSobok/SobokSobok/Presentation/Common/PagerTab/PagerTab.swift
  SobokSobok/SobokSobok/Presentation/Common/Protocol/PopUp.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Cells/FriendRequestCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Cells/PillRequestCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/ViewControllers/NoticeViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/EmptyView.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/ViewControllers/PillInfoViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/AddMedicineFirst/ViewControllers/AddMyMedicineViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/AddMedicineFirst/ViewControllers/AddPeopleViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/AddMedicineFourth/ViewControllers/AddMedicineFourthViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/AddMedicineSecond/ViewControllers/MedicineSpecificDayViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/AddMedicineThird/ViewControllers/AddMedicineThirdViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPill/ViewModel/AddPillFirstViewModel.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/PillDay/Cell/PillDayTableViewCell.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/PillPeriod/ViewController/PillPeriodViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillSecond/ViewController/AddPillSecondViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/Cell/AddPillCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/Cell/TakePillTimeCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/View/AddPillThirdView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/View/LeftAlignedCollectionViewFlowLayout.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/View/PillNameView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/ViewController/AddPillInfoViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/ViewController/AddPillThirdViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/NoFriend/View/NoFriendView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/NoFriend/ViewController/NoFriendViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/Share/SendPillFirstView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/Share/SendPillFirstViewController.swift
  SobokSobok/SobokSobok/Presentation/Splash/SplashView.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/Medicine/AddPillService.swift
Labels: 🤖 [Fix], 🍀 승찬

#219 [Style] 내 정보 탭 UI 구현
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Application/AppDelegate.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/EditNickname/EditNicknameViewController.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/EditNickname/EditNicknameViewController.xib
  SobokSobok/SobokSobok/Presentation/MyInfo/MyInfoTableViewCell.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/MyInfoTableViewCell.xib
  SobokSobok/SobokSobok/Presentation/MyInfo/MyInfoViewController.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/MyInfoViewController.xib
  SobokSobok/SobokSobok/Presentation/MyInfo/Settings/SettingViewController.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/Settings/SettingViewController.xib
  SobokSobok/SobokSobok/Resource/Image.xcassets/ic_setting_48_black.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/ic_setting_48_black.imageset/아이콘.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/ic_setting_48_black.imageset/아이콘@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/ic_setting_48_black.imageset/아이콘@3x.png
Labels: 🎨 [Style], 🍀 선영, ⚒ 내 정보

#223 [Feat] 약 추가 뷰 연결 및 Protocol 활용한 Enum 구현 (#220)
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/Main/ViewControllers/MainViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/AddMedicineSheet/ViewControllers/AddMedicineSheet.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPill/View/AddPillFirstView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPill/ViewController/AddPillFirstViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/FillLimit/ViewController/PillLimitViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillSecond/View/AddPillSecondView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillSecond/ViewController/AddPillSecondViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/ViewController/AddPillInfoViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/ViewController/AddPillThirdViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/AddUser/AddUserViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/NoFriend/ViewController/NoFriendViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/Share/SendPillFirstViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/PillStyle.swift
Labels: 📦 [Feat], 🍀 승찬

#225 [Fix] SendPillFirstViewController Bug Fix (#224)
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/Pill/AddMedicineSheet/ViewControllers/AddMedicineSheet.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/Send/SendFillFirstView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/Send/SendFillFirstViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/Send/SendPillFirstView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/Send/SendPillFirstViewController.swift
Labels: 🤖 [Fix], 🍀 승찬

#227 [Style] ToolTip 구현
  SobokSobok/SobokSobok/Common/NameSpace/Image.swift
  SobokSobok/SobokSobok/Common/Protocol/BaseProtocol.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/View/AddPillThirdView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/ViewController/AddPillThirdViewController.swift
  SobokSobok/SobokSobok/Resource/Image.xcassets/tooltipImage.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/tooltipImage.imageset/tooltipImage.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/tooltipImage.imageset/tooltipImage@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/tooltipImage.imageset/tooltipImage@3x.png
Labels: 🎨 [Style], 🍀 승찬

#222 [Fix] BaseViewController -> Protocol
  SobokSobok/SobokSobok/Presentation/Account/SaveNicknameViewController.swift
  SobokSobok/SobokSobok/Presentation/Account/SearchNicknameViewController.swift
  SobokSobok/SobokSobok/Presentation/EditFriendName/EditFriendNameViewController.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/MyInfoViewController.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/MyInfoViewController.xib
  SobokSobok/SobokSobok/Presentation/SignIn/SocialSignInViewController.swift
  SobokSobok/SobokSobok/Presentation/SignUp/CompleteSignUpViewController.swift
  SobokSobok/SobokSobok/Presentation/SignUp/SetNickNameVIewController.swift
Labels: 🕹 [Edit], 🍀 선영

#230 [Fix] PillDayTableView SectionStyle Fix (#229)
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/PillDay/ViewController/PillDayViewController.swift
Labels: 🤖 [Fix], 🍀 승찬

#232 [Feat] 내 닉네임 수정 뷰 구현
  SobokSobok/SobokSobok/Presentation/MyInfo/EditNickname/EditNicknameViewController.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/EditNickname/EditNicknameViewController.xib
Labels: 🎨 [Style], 📦 [Feat], 🍀 선영, ⚒ 내 정보

#235 [Feat] 공유 뷰 화면 작업
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Network/Foundation/APIEnvironment.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Views/FriendNameView.swift
  SobokSobok/SobokSobok/Presentation/Share/ShareViewController.swift
  SobokSobok/SobokSobok/Presentation/Share/ShareViewController.xib
  SobokSobok/SobokSobok/Presentation/Share/Views/ShareTopView.swift
Labels: 🍀 태현, 🏀 공유 탭

#234 [Style] 설정 뷰 UI 구현
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/MyInfo/EditNickname/EditNicknameViewController.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/Settings/SettingViewController.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/Settings/SettingViewController.xib
  SobokSobok/SobokSobok/Presentation/MyInfo/Settings/TermsAndPolicesViewController.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/Settings/TermsAndPolicesViewController.xib
Labels: 🎨 [Style], 📦 [Feat], 🍀 선영, ⚒ 내 정보

#238 [#236] 메인 뷰 서버 연결
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Data/DTO/APIModel/Home/Pill.swift
  SobokSobok/SobokSobok/Network/API/ScheduleEndPoint.swift
  SobokSobok/SobokSobok/Network/Service/ScheduleManager.swift
  SobokSobok/SobokSobok/Presentation/Calendar/CalendarViewController+CollectionView.swift
  SobokSobok/SobokSobok/Presentation/Calendar/CalendarViewController+FSCalendar.swift
  SobokSobok/SobokSobok/Presentation/Calendar/CalendarViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/Calendar/CalendarViewController.swift
  SobokSobok/SobokSobok/Presentation/Calendar/CalendarViewController.xib
  SobokSobok/SobokSobok/Presentation/Calendar/Views/MedicineCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Calendar/Views/MedicineCollectionViewCell.xib
  SobokSobok/SobokSobok/Presentation/Calendar/Views/TimeHeaderView.swift
  SobokSobok/SobokSobok/Presentation/Calendar/Views/TimeHeaderView.xib
  SobokSobok/SobokSobok/Presentation/Common/TabBarController.swift
  SobokSobok/SobokSobok/Presentation/Main/Cells/MainScheduleCell.swift
  SobokSobok/SobokSobok/Presentation/Main/ViewControllers/MainViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/Main/ViewControllers/MainViewController.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Cells/ScheduleCell.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController+DataSource.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController.swift
Labels: 🍀 태현, 🏚 홈 탭
