Repository TeamSobokSobok/Sobok-iOS, pull requests merged in 2022-09, with the labels that each got.

#352 [#344] 약 수정 중단, 삭제 기능 추가
  SobokSobok/SobokSobok/Presentation/Edit/ViewController/EditViewController.swift
  SobokSobok/SobokSobok/Presentation/Edit/ViewModel/EditCommonViewModel.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/MyInfoViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/MyInfoViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPill/View/ViewController/AddPillFirstViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPill/ViewModel/PillTimeViewModel.swift
Labels: 📦 [Feat], 🤖 [Fix], 🍀 승찬

#356 [#354] 디자인 QA 반영
  SobokSobok/SobokSobok/Presentation/Common/Indicator/SBIndicator.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/NoticeViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/Cell/EmptyView.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/Cell/NoticeListCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/Cell/NoticeListSection.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/NoticeListView.swift
Labels: 🎨 [Style], 🍀 은희, 🥚 알림 탭

#358 [#353] QA 1차 반영
  SobokSobok/SobokSobok/Presentation/Edit/View/EditView.swift
  SobokSobok/SobokSobok/Presentation/Edit/ViewController/EditViewController.swift
  SobokSobok/SobokSobok/Presentation/Edit/ViewModel/EditCommonViewModel.swift
  SobokSobok/SobokSobok/Presentation/Pill/AddPillSheet/ViewController/AddPillSheet.swift
  SobokSobok/SobokSobok/Presentation/Pill/AddPillSheet/ViewController/AddPillSheet.xib
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPill/View/AddPillFirstView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPill/View/ViewController/AddPillFirstViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPill/ViewModel/AddPillFirstViewModel.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPillTime/View/AddPillFirstFooterView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillSecond/View/AddPillSecondView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillSecond/ViewController/AddPillSecondViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/View/AddPillThirdView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/ViewController/AddPillThirdViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/SendPillViewModel.swift
Labels: 🤖 [Fix], 🍀 승찬

#361 [#282] 회원가입-로그인 플로우 디자인 1차 QA 반영
  SobokSobok/SobokSobok.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SobokSobok/SobokSobok/Presentation/SignIn/SocialSignInViewController.swift
  SobokSobok/SobokSobok/Presentation/SignIn/SocialSignInViewController.xib
  SobokSobok/SobokSobok/Presentation/SignUp/CompleteSignUpViewController.xib
  SobokSobok/SobokSobok/Presentation/SignUp/SetNickNameVIewController.swift
  SobokSobok/SobokSobok/Presentation/SignUp/SetNickNameVIewController.xib
  SobokSobok/SobokSobok/Resource/Image.xcassets/apple.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/apple.imageset/apple.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/apple.imageset/apple@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/apple.imageset/apple@3x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/kakao.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/kakao.imageset/kakao.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/kakao.imageset/kakao@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/kakao.imageset/kakao@3x.png
Labels: 🎨 [Style]

#365 [#360] 탈퇴 로직 구현과 푸시알림 클릭 시 이벤트 처리
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Application/AppDelegate.swift
  SobokSobok/SobokSobok/Common/Extension/Notification+Extension.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Account/UserNickNameEditModel.swift
  SobokSobok/SobokSobok/Network/API/AccountEndPoint.swift
  SobokSobok/SobokSobok/Network/Service/AccountManager.swift
  SobokSobok/SobokSobok/Presentation/Common/TabBarController.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/Settings/Terms/TermsAndPolicesViewController.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/Settings/Terms/TermsAndPolicesViewController.xib
  SobokSobok/SobokSobok/Presentation/MyInfo/Settings/Withdraw/WithdrawCompleteViewController.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/Settings/Withdraw/WithdrawViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/Settings/Withdraw/WithdrawalViewController.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/Settings/Withdraw/WithdrawalViewController.xib
  SobokSobok/SobokSobok/Presentation/MyInfo/Settings/WithdrawalViewController.swift
  SobokSobok/SobokSobok/Presentation/Share/EditFriendName/EditFriendNameViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/Share/EditFriendName/EditFriendNameViewController.swift
  SobokSobok/SobokSobok/Presentation/Share/EditFriendName/EditFriendNameViewController.xib
Labels: 📦 [Feat], 🍀 은희
