Repository TeamSobokSobok/Sobok-iOS, pull requests merged in 2022-01, with the labels that each got.

#11 [#10] 네임스페이스용 파이썬 스크립트 추가
  .gitignore
  SobokSobok/SobokSobok/Support/Script/generate.py
Labels: ✚ [Add], 🍀 태현, 🚨 빠른리뷰필요

#15 [#12] 약 추가 바텀 시트 구현
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSheet/AddMedicineSheet.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSheet/AddMedicineSheet.xib
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSheet/AddMedicineTableViewCell.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSheet/AddMedicineTableViewCell.xib
Labels: 🎨 [Style], 🍀 승찬

#19 [Fix] generate.py 수정
  SobokSobok/SobokSobok/Support/Script/generate.py
Labels: 🤖 [Fix], 🍀 선영

#18 [#13] 알림탭 첫번째 뷰 구현
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Data/Model/NoticeListDataModel.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeTableViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeTableViewCell.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeViewController.xib
Labels: 🎨 [Style], 📦 [Feat], 🍀 은희

#21 [#13] 코드리뷰 반영
  SobokSobok/SobokSobok/Data/Model/NoticeListDataModel.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeTableViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeViewController.swift
Labels: 🤖 [Fix], 🍀 은희

#23 [#14] 하단 탭 바 구현
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SobokSobok/SobokSobok/Presentation/Common/TabBarController.swift
  SobokSobok/SobokSobok/Presentation/Common/TabBarItem.swift
  SobokSobok/SobokSobok/Resource/Image.xcassets/icAlarmActive.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/icHomeActive.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/icPlusActive.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/icShareActive.imageset/Contents.json
Labels: 🎨 [Style], 🍀 태현

#24 [#22] 커스텀 네비게이션바 구현
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/Common/NavigationBarViewController.swift
  SobokSobok/SobokSobok/Presentation/Common/NavigationBarViewController.xib
Labels: 🎨 [Style], 🍀 은희

#26 [#22] 클래스 변경
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/Common/NavigationBarView.swift
  SobokSobok/SobokSobok/Presentation/Common/NavigationBarView.xib
Labels: 🤖 [Fix], 🍀 은희

#27 [#2] 리드미 작성
  Asset/sobok-logo.png
  Asset/선영.png
  Asset/승찬.png
  Asset/은희.png
  Asset/태현.png
  README.md
Labels: 🔖 Docs, 🍀 태현

#30 [#28] 홈 뷰 UI 영역 잡기
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SobokSobok/SobokSobok/Presentation/Common/BaseViewController.swift
  SobokSobok/SobokSobok/Presentation/Common/TabBarController.swift
  SobokSobok/SobokSobok/Presentation/Home/HomeViewController.swift
  SobokSobok/SobokSobok/Presentation/Home/HomeViewController.xib
  SobokSobok/SobokSobok/Presentation/Home/MedicineCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Home/MedicineCollectionViewCell.xib
  SobokSobok/SobokSobok/Presentation/Home/TimeHeaderView.swift
  SobokSobok/SobokSobok/Presentation/Home/TimeHeaderView.xib
Labels: 🎨 [Style], 🍀 태현, 🏚 홈 탭

#34 [#31] 공유탭 UI 영역 구현
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/Common/TabBarController.swift
  SobokSobok/SobokSobok/Presentation/Share/ShareViewController.swift
  SobokSobok/SobokSobok/Presentation/Share/ShareViewController.xib
  SobokSobok/SobokSobok/Resource/Image.xcassets/icPencil32.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/icPencil48.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/icPlus48.imageset/Contents.json
Labels: 🎨 [Style], 🍀 태현, 공유 탭

#36 [Edit] 파이썬 스크립트 수정 (#35)
  SobokSobok/SobokSobok/Common/NameSpace/Color.swift
  SobokSobok/SobokSobok/Common/NameSpace/Image.swift
  SobokSobok/SobokSobok/Presentation/Common/TabBarController.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMyMedicineView/AddMyMedicineCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMyMedicineView/AddMyMedicineFooterView.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMyMedicineView/AddMyMedicineView.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMyMedicineView/AddPeopleViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeTableViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeViewController.swift
  SobokSobok/SobokSobok/Support/Script/generate.py
Labels: 🕹 [Edit], 🍀 태현, 🚨 빠른리뷰필요

#29 [#20] 로그인, 회원가입 뷰 UI
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/Common/NavigationBarView.xib
  SobokSobok/SobokSobok/Presentation/SignIn/SignInViewController.swift
  SobokSobok/SobokSobok/Presentation/SignIn/SignInViewController.xib
  SobokSobok/SobokSobok/Presentation/SignUp/SignUpViewController.swift
  SobokSobok/SobokSobok/Presentation/SignUp/SignUpViewController.xib
  SobokSobok/SobokSobok/Resource/Base.lproj/LaunchScreen.storyboard
Labels: 🎨 [Style], 📦 [Feat], 🍀 선영

#40 [Style] 약 추가2 UI 구현
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SobokSobok/SobokSobok/Application/SceneDelegate.swift
  SobokSobok/SobokSobok/Common/NameSpace/Image.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineFirst/Cells/AddMyMedicineCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineFirst/Cells/AddMyMedicineCollectionViewCell.xib
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineFirst/ViewControllers/AddMyMedicineViewController.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineFirst/ViewControllers/AddPeopleViewController.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineFirst/ViewControllers/AddPeopleViewController.xib
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineFirst/Views/AddMyMedicineFooterView.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineFirst/Views/AddMyMedicineView.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSecond/AddMedicineSecondViewController.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSecond/AddMedicineSecondViewController.xib
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSecond/MedicineCalendarViewController.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSecond/MedicineCalendarViewController.xib
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSecond/MedicineDayTableViewCell.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSecond/MedicineDayTableViewCell.xib
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSecond/MedicineSpecificDayViewController.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSecond/MedicineSpecificDayViewController.xib
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSecond/MedicineSpecificPeriodViewController.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSecond/MedicineSpecificPeriodViewController.xib
  SobokSobok/SobokSobok/Resource/Image.xcassets/icBackSmall48.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/icBackSmall48.imageset/icBackSmall48.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/icBackSmall48.imageset/icBackSmall48@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/icBackSmall48.imageset/icBackSmall48@3x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/icCheckButton48.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/icCheckButton48.imageset/icCheckButton.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/icCheckButton48.imageset/icCheckButton@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/icCheckButton48.imageset/icCheckButton@3x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/icVCheck.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/icVCheck.imageset/icVCheck.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/icVCheck.imageset/icVCheck@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/icVCheck.imageset/icVCheck@3x.png
Labels: 🎨 [Style], 🍀 승찬

#42 [#9] 폰트 및 타이포스타일 작업
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Common/DesignSystem/TypoStyle.swift
  SobokSobok/SobokSobok/Common/Extension/UIFont+Extension.swift
  SobokSobok/SobokSobok/Common/NameSpace/Font.swift
  SobokSobok/SobokSobok/Presentation/Common/Sample/SampleViewController.swift
  SobokSobok/SobokSobok/Presentation/Common/Sample/SampleViewController.xib
  SobokSobok/SobokSobok/Resource/Font/Pretendard-Black.otf
  SobokSobok/SobokSobok/Resource/Font/Pretendard-ExtraBold.otf
  SobokSobok/SobokSobok/Resource/Font/Pretendard-Medium.otf
  SobokSobok/SobokSobok/Resource/Font/Pretendard-Thin.otf
  SobokSobok/SobokSobok/Support/Info.plist
Labels: 🎨 [Style], 🍀 태현, 💣 [Test], 🚨 빠른리뷰필요

#43 [Fix] 바텀 시트 오토레이아웃, 애니메이션 추가
  SobokSobok/SobokSobok/Application/SceneDelegate.swift
  SobokSobok/SobokSobok/Presentation/Common/TabBarController.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSheet/AddMedicineSheet.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSheet/AddMedicineSheet.xib
Labels: 🤖 [Fix], 🍀 승찬

#51 [#44] 바텀시트 UI 구현
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Common/NameSpace/Image.swift
  SobokSobok/SobokSobok/Presentation/Common/Sheet/StickerBottomSheet/StickerBottomSheet.swift
  SobokSobok/SobokSobok/Presentation/Common/Sheet/StickerBottomSheet/StickerBottomSheet.xib
  SobokSobok/SobokSobok/Presentation/Common/Sheet/StickerCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Common/Sheet/StickerCollectionViewCell.xib
  SobokSobok/SobokSobok/Presentation/Home/HomeViewController.swift
  SobokSobok/SobokSobok/Presentation/Home/Views/MedicineCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Home/Views/MedicineCollectionViewCell.xib
  SobokSobok/SobokSobok/Presentation/Home/Views/TimeHeaderView.swift
  SobokSobok/SobokSobok/Presentation/Home/Views/TimeHeaderView.xib
  SobokSobok/SobokSobok/Resource/Image.xcassets/icSobok.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/icSobok.imageset/icSobok.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/icSobok.imageset/icSobok@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/icSobok.imageset/icSobok@3x.png
Labels: 🎨 [Style], 🍀 태현

#54 [#53] 캘린더 UI 구현
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SobokSobok/SobokSobok/Common/DesignSystem/TypoStyle.swift
  SobokSobok/SobokSobok/Common/NameSpace/Image.swift
  SobokSobok/SobokSobok/Presentation/Common/TabBarController.swift
  SobokSobok/SobokSobok/Presentation/Common/Views/CalendarDayCell.swift
  SobokSobok/SobokSobok/Presentation/Home/MainViewController.swift
  SobokSobok/SobokSobok/Presentation/Home/MainViewController.xib
  SobokSobok/SobokSobok/Presentation/Home/Views/MedicineCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Home/Views/MedicineCollectionViewCell.xib
  SobokSobok/SobokSobok/Presentation/Home/Views/TimeHeaderView.swift
  SobokSobok/SobokSobok/Presentation/Home/Views/TimeHeaderView.xib
  SobokSobok/SobokSobok/Resource/Image.xcassets/icArrowDropDown14.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/icArrowDropDown14.imageset/Frame 5006.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/icArrowDropDown14.imageset/Frame 5006@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/icArrowDropDown14.imageset/Frame 5006@3x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/icArrowDropDown48.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/icArrowDropDown48.imageset/icArrowDropDown48.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/icArrowDropDown48.imageset/icArrowDropDown48@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/icArrowDropDown48.imageset/icArrowDropDown48@3x.png
Labels: 🎨 [Style], 📦 [Feat], 🍀 태현, 🚨 빠른리뷰필요, 🏚 홈 탭

#50 [#25] 약 전송 요청 확인뷰 UI 구현
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Common/NameSpace/Image.swift
  SobokSobok/SobokSobok/Data/Model/SendInfoListDataModel.swift
  SobokSobok/SobokSobok/Presentation/Common/NavigationBarView.swift
  SobokSobok/SobokSobok/Presentation/Common/NavigationBarView.xib
  SobokSobok/SobokSobok/Presentation/Notice/FooterCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/FooterCollectionViewCell.xib
  SobokSobok/SobokSobok/Presentation/Notice/SendInfoCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/SendInfoCollectionViewCell.xib
  SobokSobok/SobokSobok/Presentation/Notice/SendInfoViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/SendInfoViewController.xib
  SobokSobok/SobokSobok/Presentation/Notice/SenderInfoCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/SenderInfoCollectionViewCell.xib
  SobokSobok/SobokSobok/Resource/Image.xcassets/Ellipse38.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/Ellipse38.imageset/Ellipse38.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/Ellipse38.imageset/Ellipse38@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/Ellipse38.imageset/Ellipse38@3x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/Ellipse64.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/Ellipse64.imageset/Ellipse64.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/Ellipse64.imageset/Ellipse64@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/Ellipse64.imageset/Ellipse64@3x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/Ellipse65.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/Ellipse65.imageset/Ellipse65.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/Ellipse65.imageset/Ellipse65@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/Ellipse65.imageset/Ellipse65@3x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/Ellipse94.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/Ellipse94.imageset/Ellipse94.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/Ellipse94.imageset/Ellipse94@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/Ellipse94.imageset/Ellipse94@3x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/Ellipse95.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/Ellipse95.imageset/Ellipse95.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/Ellipse95.imageset/Ellipse95@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/Ellipse95.imageset/Ellipse95@3x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/Union.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/Union.imageset/Union.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/Union.imageset/Union@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/Union.imageset/Union@3x.png
Labels: 🎨 [Style], 🍀 은희, 🥚 알림 탭

#59 [Feat] 회원가입 기능 구현
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Application/AppDelegate.swift
  SobokSobok/SobokSobok/Presentation/SignIn/SignInViewController.swift
  SobokSobok/SobokSobok/Presentation/SignIn/SignInViewController.xib
  SobokSobok/SobokSobok/Presentation/SignUp/CompleteSignUpViewController.swift
  SobokSobok/SobokSobok/Presentation/SignUp/CompleteSignUpViewController.xib
  SobokSobok/SobokSobok/Presentation/SignUp/SetNickNameVIewController.swift
  SobokSobok/SobokSobok/Presentation/SignUp/SetNickNameVIewController.xib
  SobokSobok/SobokSobok/Presentation/SignUp/SignUpViewController.swift
  SobokSobok/SobokSobok/Presentation/SignUp/SignUpViewController.xib
Labels: 🎨 [Style], 📦 [Feat], 🍀 선영

#63 [#52] 복약 정보 수정 뷰 UI 구현
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/NoticeTableViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/NoticeTableViewCell.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/NoticeViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/NoticeViewController.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThrid/MedicineInfoEditViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThrid/MedicineInfoEditViewController.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThrid/MedicineTimeFooterView.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThrid/MedicineTimeFooterView.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThrid/MedicineTimeInfoCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThrid/MedicineTimeInfoCollectionViewCell.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThrid/TermSelectViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThrid/TermSelectViewController.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThrid/WeekSelectTableViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThrid/WeekSelectTableViewCell.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThrid/WeekSelectViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThrid/WeekSelectViewController.xib
  SobokSobok/SobokSobok/Resource/Image.xcassets/timePlusIcon.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/timePlusIcon.imageset/timePlusIcon.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/timePlusIcon.imageset/timePlusIcon@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/timePlusIcon.imageset/timePlusIcon@3x.png
Labels: 🎨 [Style], 🍀 은희, 🥚 알림 탭

#69 [Fix] 리셋된 레포 빌드되도록 수정
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineThird/MedicineTimeViewController.swift
Labels: 🤖 [Fix], 🚨 빠른리뷰필요

#76 [#74] Moya 세팅, getMyPillCount 서버 연결
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Common/NameSpace/URL.swift
  SobokSobok/SobokSobok/Common/NameSpace/URLs.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Medicine/PillCountModel.swift
  SobokSobok/SobokSobok/Presentation/Common/Sample/SampleViewController.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineFourth/AddMedicineFourthViewController.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/GenericResponse.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/Medicine/PillCountAPI.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/Medicine/PillCountService.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/NetworkResult.swift
  SobokSobok/SobokSobok/Support/Info.plist
Labels: ✚ [Add], 🍀 승찬

#71 [#52] 복약 정보 수정 뷰 UI 구현
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/NoticeTableViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/NoticeTableViewCell.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/NoticeViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/NoticeViewController.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThrid/MedicineInfoEditViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThrid/MedicineInfoEditViewController.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThrid/MedicineTimeFooterView.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThrid/MedicineTimeFooterView.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThrid/MedicineTimeInfoCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThrid/MedicineTimeInfoCollectionViewCell.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThrid/TermSelectViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThrid/TermSelectViewController.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThrid/WeekSelectTableViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThrid/WeekSelectTableViewCell.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThrid/WeekSelectViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThrid/WeekSelectViewController.xib
  SobokSobok/SobokSobok/Resource/Image.xcassets/timePlusIcon.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/timePlusIcon.imageset/timePlusIcon.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/timePlusIcon.imageset/timePlusIcon@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/timePlusIcon.imageset/timePlusIcon@3x.png
Labels: 🎨 [Style], 🍀 은희, 🥚 알림 탭

#78 [Fix] 스티커 보내기 팝업창 UI 재구현
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/Share/SendStickerPopUpViewController.swift
  SobokSobok/SobokSobok/Presentation/Share/SendStickerPopUpViewController.xib
Labels: 🎨 [Style], 🍀 은희, 🏀 공유 탭

#83 [#62] 약 추가뷰 연결
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Common/NameSpace/URLs.swift
  SobokSobok/SobokSobok/Presentation/Common/TabBarController.swift
  SobokSobok/SobokSobok/Presentation/Home/MainViewController.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineFirst/ViewControllers/AddMyMedicineViewController.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineFirst/Views/AddMyMedicineView.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineFourth/Cells/MedicineInfoCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineFourth/Cells/MedicineInfoCollectionViewCell.xib
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineFourth/ViewControllers/AddMedicineFourthViewController.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineFourth/ViewControllers/AddMedicineFourthViewController.xib
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineFourth/Views/MedicineInfoHeaderView.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSecond/Cells/MedicineDayTableViewCell.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSecond/Cells/MedicineDayTableViewCell.xib
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSecond/MedicineCalendarViewController.xib
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSecond/ViewControllers/AddMedicineSecondViewController.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSecond/ViewControllers/AddMedicineSecondViewController.xib
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSecond/ViewControllers/MedicineCalendarViewController.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSecond/ViewControllers/MedicineCalendarViewController.xib
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSecond/ViewControllers/MedicineSpecificDayViewController.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSecond/ViewControllers/MedicineSpecificDayViewController.xib
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSecond/ViewControllers/MedicineSpecificPeriodViewController.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSecond/ViewControllers/MedicineSpecificPeriodViewController.xib
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSheet/Cells/AddMedicineTableViewCell.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSheet/Cells/AddMedicineTableViewCell.xib
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSheet/ViewControllers/AddMedicineSheet.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSheet/ViewControllers/AddMedicineSheet.xib
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineThird/Cells/AddTimeCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineThird/Cells/AddTimeCollectionViewCell.xib
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineThird/ViewControllers/AddMedicineThirdViewController.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineThird/ViewControllers/AddMedicineThirdViewController.xib
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineThird/ViewControllers/MedicineTimeViewController.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineThird/ViewControllers/MedicineTimeViewController.xib
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineThird/Views/AddMedicineTimeFooterView.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeViewController.swift
  SobokSobok/SobokSobok/Presentation/Share/ShareViewController.swift
Labels: 🎨 [Style], 🍀 승찬

#86 [#85] 캘린더뷰(메인, 공유에서 사용) UI 수정 작업
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SobokSobok/SobokSobok/Common/Extension/Date+Extension.swift
  SobokSobok/SobokSobok/Common/NameSpace/Image.swift
  SobokSobok/SobokSobok/Common/NameSpace/URLs.swift
  SobokSobok/SobokSobok/Presentation/Common/Sheet/StickerBottomSheet/StickerBottomSheet.swift
  SobokSobok/SobokSobok/Presentation/Common/Sheet/StickerBottomSheet/StickerBottomSheet.xib
  SobokSobok/SobokSobok/Presentation/Common/Views/CalendarDayCell.swift
  SobokSobok/SobokSobok/Presentation/Home/Calendar/CalendarViewController+CollectionViewDataSource.swift
  SobokSobok/SobokSobok/Presentation/Home/Calendar/CalendarViewController+FSCalendar.swift
  SobokSobok/SobokSobok/Presentation/Home/Calendar/CalendarViewController.swift
  SobokSobok/SobokSobok/Presentation/Home/Calendar/CalendarViewController.xib
  SobokSobok/SobokSobok/Presentation/Home/HomeViewController.swift
  SobokSobok/SobokSobok/Presentation/Home/HomeViewController.xib
  SobokSobok/SobokSobok/Presentation/Home/MainViewController.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineFirst/Views/AddMyMedicineFooterView.swift
  SobokSobok/SobokSobok/Presentation/Share/ShareViewController.swift
  SobokSobok/SobokSobok/Resource/Image.xcassets/calendarBackgroundToday.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/calendarBackgroundToday.imageset/calendarBackgroundToday.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/calendarBackgroundToday.imageset/calendarBackgroundToday@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/calendarBackgroundToday.imageset/calendarBackgroundToday@3x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustHome.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustHome.imageset/illustHome.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustHome.imageset/illustHome@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustHome.imageset/illustHome@3x.png
Labels: 🎨 [Style], 🍀 태현, 🏚 홈 탭, 🏀 공유 탭

#92 [#91] 로그인 뷰 서버통신
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Data/DTO/APIModel/SignInModel.swift
  SobokSobok/SobokSobok/Presentation/SignIn/SignInViewController.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/SignIn/SignInAPI.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/SignIn/SignInService.swift
Labels: 📦 [Feat], 🍀 선영

#94 [#93] 닉네임 중복 확인 서버통신
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Data/DTO/APIModel/CheckUsernameModel.swift
  SobokSobok/SobokSobok/Presentation/SignUp/SetNickNameVIewController.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/SignUp/CheckUsernameAPI.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/SignUp/CheckUsernameService.swift
Labels: 📦 [Feat], 🍀 선영

#95 [#87] 홈뷰 API 연결 작업
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Data/DTO/APIModel/Home/Pill.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Home/Schedule.swift
  SobokSobok/SobokSobok/Presentation/Home/Calendar/CalendarViewController+CollectionViewDataSource.swift
  SobokSobok/SobokSobok/Presentation/Home/Calendar/CalendarViewController+FSCalendar.swift
  SobokSobok/SobokSobok/Presentation/Home/Calendar/CalendarViewController.swift
  SobokSobok/SobokSobok/Presentation/Home/Calendar/CalendarViewController.xib
  SobokSobok/SobokSobok/Presentation/Home/HomeViewController.swift
  SobokSobok/SobokSobok/Presentation/Home/HomeViewController.xib
  SobokSobok/SobokSobok/Presentation/Home/Views/MedicineCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Share/ShareViewController.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/APIConstants.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/Home/ScheduleAPI.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/Home/ScheduleService.swift
Labels: 📦 [Feat], 🍀 태현, 🏚 홈 탭

#98 [#96] 일러스트 추가
  SobokSobok/SobokSobok/Presentation/SignUp/CompleteSignUpViewController.xib
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustAddFriend.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustAddFriend.imageset/Group 1348.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustAddFriend.imageset/Group 1348@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustAddFriend.imageset/Group 1348@3x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustAlreadyFivePills.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustAlreadyFivePills.imageset/Group 1350.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustAlreadyFivePills.imageset/Group 1350@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustAlreadyFivePills.imageset/Group 1350@3x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustNoFriend.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustNoFriend.imageset/Group 1348.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustNoFriend.imageset/Group 1348@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustNoFriend.imageset/Group 1348@3x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustNoNotice.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustNoNotice.imageset/Group 1340.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustNoNotice.imageset/Group 1340@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustNoNotice.imageset/Group 1340@3x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustNoPill.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustNoPill.imageset/Group 1347.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustNoPill.imageset/Group 1347@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustNoPill.imageset/Group 1347@3x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustNoSearchResult.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustNoSearchResult.imageset/Group 1340.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustNoSearchResult.imageset/Group 1340@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustNoSearchResult.imageset/Group 1340@3x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustWelcome.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustWelcome.imageset/Group 1348.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustWelcome.imageset/Group 1348@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustWelcome.imageset/Group 1348@3x.png
Labels: ✚ [Add], 🍀 선영

#100 [#99] 로그인/회원가입 플로우 폰트수정
  SobokSobok/SobokSobok/Presentation/SignIn/SignInViewController.xib
  SobokSobok/SobokSobok/Presentation/SignUp/SetNickNameVIewController.xib
  SobokSobok/SobokSobok/Presentation/SignUp/SignUpViewController.xib
Labels: 🎨 [Style], 🍀 선영

#106 [#105] 계정 공유 요청 - 닉네임 저장 뷰 구현
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/Account/SaveNicknameViewController.swift
  SobokSobok/SobokSobok/Presentation/Account/SaveNicknameViewController.xib
  SobokSobok/SobokSobok/Presentation/Account/SearchNicknameViewController.swift
Labels: 🎨 [Style], 📦 [Feat], 🍀 선영

#110 [#109] 약 복용 중단, 약 삭제 API 연결
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Common/Extension/UIViewController+Extension.swift
  SobokSobok/SobokSobok/Presentation/Home/Calendar/CalendarViewController+CollectionViewDataSource.swift
  SobokSobok/SobokSobok/Presentation/Home/Calendar/CalendarViewController.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/Home/PillManagementAPI.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/Home/PillManagementService.swift
Labels: 📦 [Feat], 🍀 태현, 🏀 공유 탭

#113 [#111] 홈 탭 구조 정리
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Common/NameSpace/URLs.swift
  SobokSobok/SobokSobok/Presentation/Calendar/CalendarViewController+CollectionView.swift
  SobokSobok/SobokSobok/Presentation/Calendar/CalendarViewController+FSCalendar.swift
  SobokSobok/SobokSobok/Presentation/Calendar/CalendarViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/Calendar/CalendarViewController.swift
  SobokSobok/SobokSobok/Presentation/Calendar/CalendarViewController.xib
  SobokSobok/SobokSobok/Presentation/Calendar/Views/MedicineCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Calendar/Views/MedicineCollectionViewCell.xib
  SobokSobok/SobokSobok/Presentation/Calendar/Views/TimeHeaderView.swift
  SobokSobok/SobokSobok/Presentation/Calendar/Views/TimeHeaderView.xib
  SobokSobok/SobokSobok/Presentation/Home/Calendar/CalendarViewController+ShareAPI.swift
Labels: 🕹 [Edit], 🍀 태현, 🏚 홈 탭

#116 [#115] 계정 공유 요청 - 닉네임 검색 뷰 서버연결
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Data/DTO/APIModel/Account/SearchNicknameModel.swift
  SobokSobok/SobokSobok/Data/Model/SearchNicknameDataModel.swift
  SobokSobok/SobokSobok/Presentation/Account/SaveNicknameViewController.swift
  SobokSobok/SobokSobok/Presentation/Account/SearchNicknameViewController.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/Account/AddAccontAPI.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/Account/AddAccountService.swift
Labels: 📦 [Feat], 🍀 선영

#118 [#114] 메인탭, 공유탭 UI 업데이트
  SobokSobok/SobokSobok/Common/Extension/Date+Extension.swift
  SobokSobok/SobokSobok/Common/NameSpace/Image.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Home/Pill.swift
  SobokSobok/SobokSobok/Presentation/Calendar/CalendarViewController+CollectionView.swift
  SobokSobok/SobokSobok/Presentation/Calendar/CalendarViewController+FSCalendar.swift
  SobokSobok/SobokSobok/Presentation/Calendar/CalendarViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/Calendar/CalendarViewController.swift
  SobokSobok/SobokSobok/Presentation/Calendar/CalendarViewController.xib
  SobokSobok/SobokSobok/Presentation/Calendar/Views/MedicineCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Share/ShareViewController.swift
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustNoShare.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustNoShare.imageset/illustNoShare.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustNoShare.imageset/illustNoShare@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustNoShare.imageset/illustNoShare@3x.png
  SobokSobok/SobokSobok/Service/Network/APIServices/Share/ShareAPI.swift
Labels: 🎨 [Style], 🤖 [Fix], 🍀 태현, 🏚 홈 탭, 🏀 공유 탭

#120 [#117] 이름 저장 뷰 서버연결
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Data/DTO/APIModel/Account/SaveNicknameModel.swift
  SobokSobok/SobokSobok/Data/Model/SearchNicknameDataModel.swift
  SobokSobok/SobokSobok/Presentation/Account/SaveNicknameViewController.swift
  SobokSobok/SobokSobok/Presentation/Account/SearchNicknameViewController.xib
  SobokSobok/SobokSobok/Presentation/Common/BaseViewController.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/Account/AddAccontAPI.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/Account/AddAccountService.swift
Labels: 📦 [Feat], 🍀 선영

#122 [#121] 이름 수정 뷰 구현
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/EditFriendName/EditFriendNameViewController.swift
  SobokSobok/SobokSobok/Presentation/EditFriendName/EditFriendNameViewController.xib
Labels: 🎨 [Style], 📦 [Feat], 🍀 선영, 🏀 공유 탭

#124 [#112] 약 추가 서버 통신, 나 / 친구 플로우 구별, 약 추가 0개 일 때 뷰 연결
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Common/NameSpace/Image.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Medicine/AddPill.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Medicine/PillCount.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineFirst/Cells/AddMyMedicineCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineFirst/ViewControllers/AddMyMedicineViewController.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineFirst/Views/AddMyMedicineFooterView.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineFourth/ViewControllers/AddMedicineFourthViewController.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineFourth/ViewControllers/AddMedicineFourthViewController.xib
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineFourth/ViewControllers/SendPillInfoViewController.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineFourth/ViewControllers/SendPillInfoViewController.xib
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineFourth/Views/MedicineInfoHeaderView.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSecond/ViewControllers/AddMedicineSecondViewController.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSecond/ViewControllers/AddMedicineSecondViewController.xib
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSheet/ViewControllers/AddMedicineSheet.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineThird/ViewControllers/AddMedicineThirdViewController.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineThird/ViewControllers/AddMedicineThirdViewController.xib
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineThird/Views/AddMedicineTimeFooterView.swift
  SobokSobok/SobokSobok/Presentation/Medicine/FillLimit/ViewControllers/PillLimitViewController.swift
  SobokSobok/SobokSobok/Presentation/Medicine/FillLimit/Views/PillLimitView.swift
  SobokSobok/SobokSobok/Presentation/SignIn/SignInViewController.xib
  SobokSobok/SobokSobok/Resource/Image.xcassets/icCloseFill.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/icCloseFill.imageset/icCloseFill.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/icCloseFill.imageset/icCloseFill@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/icCloseFill.imageset/icCloseFill@3x.png
  SobokSobok/SobokSobok/Service/Network/APIServices/Medicine/AddPillAPI.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/Medicine/AddPillService.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/Medicine/PillCountAPI.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/Medicine/PillCountService.swift
Labels: 📦 [Feat], 🍀 승찬

#127 [#123] 로그인/회원가입 뷰 디자인 QA 피드백 반영
  SobokSobok/SobokSobok/Presentation/Account/SaveNicknameViewController.swift
  SobokSobok/SobokSobok/Presentation/Account/SaveNicknameViewController.xib
  SobokSobok/SobokSobok/Presentation/Account/SearchNicknameViewController.swift
  SobokSobok/SobokSobok/Presentation/SignIn/SignInViewController.swift
  SobokSobok/SobokSobok/Presentation/SignIn/SignInViewController.xib
  SobokSobok/SobokSobok/Presentation/SignUp/CompleteSignUpViewController.swift
  SobokSobok/SobokSobok/Presentation/SignUp/CompleteSignUpViewController.xib
  SobokSobok/SobokSobok/Presentation/SignUp/SetNickNameVIewController.swift
  SobokSobok/SobokSobok/Presentation/SignUp/SetNickNameVIewController.xib
  SobokSobok/SobokSobok/Presentation/SignUp/SignUpViewController.swift
  SobokSobok/SobokSobok/Presentation/SignUp/SignUpViewController.xib
Labels: 🎨 [Style], 🍀 선영

#128 [#125] 친구 이름 수정 서버 연결
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Data/DTO/APIModel/Share/EditFriendUsername.swift
  SobokSobok/SobokSobok/Data/Model/EditFriendDataModel.swift
  SobokSobok/SobokSobok/Presentation/EditFriendName/EditFriendNameViewController.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/Share/ShareAPI.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/Share/ShareService.swift
Labels: 📦 [Feat], 🍀 선영, 🏀 공유 탭, 🌐 서버연결

#135 [Fix] Lint 규칙 수정 및 적용 (#134)
  SobokSobok/.swiftlint.yml
  SobokSobok/SobokSobok/Data/DTO/APIModel/Medicine/AddPill.swift
  SobokSobok/SobokSobok/Presentation/Common/Sample/SampleViewController.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineFourth/ViewControllers/SendPillInfoViewController.swift
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSheet/ViewControllers/AddMedicineSheet.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/Medicine/AddPillAPI.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/Medicine/AddPillService.swift
Labels: 🤖 [Fix], 🍀 태현

#137 [#136] Notice Third 파일 및 폴더 추가
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThird/Cells/PillTimeInfoCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThird/Cells/PillTimeInfoCollectionViewCell.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThird/Cells/WeekSelectTableViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThird/Cells/WeekSelectTableViewCell.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThird/ViewControllers/PillInfoEditViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThird/ViewControllers/PillInfoEditViewController.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThird/ViewControllers/TermSelectViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThird/ViewControllers/TermSelectViewController.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThird/ViewControllers/WeekSelectViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThird/ViewControllers/WeekSelectViewController.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThird/Views/PillTimeInfoFooterView.swift
Labels: 🤖 [Fix], 🍀 은희, 🚨 빠른리뷰필요

#130 [#129] 로그인/회원가입 서버 관련 코드 정리
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Data/DTO/APIModel/CheckUsernameModel.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Sign.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/SignInModel.swift
  SobokSobok/SobokSobok/Data/Model/SignUpDataModel.swift
  SobokSobok/SobokSobok/Presentation/SignIn/SignInViewController.swift
  SobokSobok/SobokSobok/Presentation/SignUp/SetNickNameVIewController.swift
  SobokSobok/SobokSobok/Presentation/SignUp/SignUpViewController.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/Sign/SignAPI.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/Sign/SignService.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/SignIn/SignInAPI.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/SignIn/SignInService.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/SignUp/CheckUsernameAPI.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/SignUp/CheckUsernameService.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/SignUp/SignUpAPI.swift
Labels: 🕹 [Edit], ❌ [Del], 🍀 선영, 🌐 서버연결

#139 [#138] 네비게이션 바 오토레이아웃 재설정
  SobokSobok/SobokSobok/Presentation/Account/SaveNicknameViewController.xib
  SobokSobok/SobokSobok/Presentation/Account/SearchNicknameViewController.xib
  SobokSobok/SobokSobok/Presentation/EditFriendName/EditFriendNameViewController.xib
  SobokSobok/SobokSobok/Presentation/SignUp/CompleteSignUpViewController.xib
  SobokSobok/SobokSobok/Presentation/SignUp/SetNickNameVIewController.swift
  SobokSobok/SobokSobok/Presentation/SignUp/SetNickNameVIewController.xib
  SobokSobok/SobokSobok/Presentation/SignUp/SignUpViewController.swift
  SobokSobok/SobokSobok/Presentation/SignUp/SignUpViewController.xib
Labels: 🎨 [Style], 🤖 [Fix], 🍀 선영

#140 [#132] 알림탭 플로우 연결과 디자인 QA 부분 반영
  SobokSobok/SobokSobok/Presentation/Notice/NoticeTableViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeTableViewCell.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThird/ViewControllers/PillInfoEditViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThird/ViewControllers/PillInfoEditViewController.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThird/Views/PillTimeInfoFooterView.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeViewController.xib
  SobokSobok/SobokSobok/Presentation/Notice/SendInfoCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/SendInfoCollectionViewCell.xib
  SobokSobok/SobokSobok/Presentation/Notice/SendInfoViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/SendInfoViewController.xib
  SobokSobok/SobokSobok/Presentation/Notice/SenderInfoCollectionViewCell.xib
Labels: 🎨 [Style], 📦 [Feat], 🍀 은희, 🥚 알림 탭

#144 [#133] 홈탭, 공유탭 디자인 1차 QA 반영
  SobokSobok/SobokSobok/Common/DesignSystem/TypoStyle.swift
  SobokSobok/SobokSobok/Common/Extension/Date+Extension.swift
  SobokSobok/SobokSobok/Presentation/Calendar/CalendarViewController+CollectionView.swift
  SobokSobok/SobokSobok/Presentation/Calendar/CalendarViewController+FSCalendar.swift
  SobokSobok/SobokSobok/Presentation/Calendar/CalendarViewController.swift
  SobokSobok/SobokSobok/Presentation/Calendar/Views/MedicineCollectionViewCell.xib
  SobokSobok/SobokSobok/Presentation/Common/PagerTab/PagerTab.swift
  SobokSobok/SobokSobok/Presentation/Home/HomeViewController.xib
  SobokSobok/SobokSobok/Presentation/Share/ShareViewController.xib
  SobokSobok/SobokSobok/Service/Network/APIServices/APIConstants.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/Home/PillManagementService.swift
Labels: 🎨 [Style], 🤖 [Fix], 🍀 태현, 🏚 홈 탭, 🏀 공유 탭

#146 [#141] ReadMe 최종과제 내용 반영
  README.md
Labels: 🔖 Docs, 🍀 선영

#156 [#145] 디자인 QA 1차 반영
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/Medicine/AddMedicineSecond/ViewControllers/AddMedicineSecondViewController.xib
  SobokSobok/SobokSobok/Presentation/Notice/FooterCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/FooterCollectionViewCell.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeTableViewCell.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThird/ViewControllers/PillInfoEditViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThird/ViewControllers/PillInfoEditViewController.xib
  SobokSobok/SobokSobok/Presentation/Notice/SendInfoCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Splash/SplashView.swift
  SobokSobok/SobokSobok/Presentation/Splash/SplashView.xib
Labels: 🎨 [Style], 🍀 은희, 🥚 알림 탭

#158 [#155] 스플래쉬 뷰 구현
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/Notice/NoticeTableViewCell.xib
  SobokSobok/SobokSobok/Presentation/Splash/SplashView.swift
  SobokSobok/SobokSobok/Presentation/Splash/SplashView.xib
  SobokSobok/SobokSobok/Resource/Gif/splash.json
Labels: 🎨 [Style], 🍀 은희

#160 [#159] 초기 뷰 플로우 연결
  SobokSobok/SobokSobok/Application/SceneDelegate.swift
  SobokSobok/SobokSobok/Presentation/Splash/SplashView.swift
  SobokSobok/SobokSobok/Presentation/Splash/SplashView.xib
Labels: 📦 [Feat], 🍀 은희
