Repository TeamSobokSobok/Sobok-iOS, pull requests merged in 2022-10, with the labels that each got.

#368 [#367] 홈 화면 이번 달 아닌 달 정보는 캘린더에 표시되지 않는 이슈 수정
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Data/DTO/APIModel/Home/Schedule.swift
  SobokSobok/SobokSobok/Network/Foundation/APIEnvironment.swift
  SobokSobok/SobokSobok/Network/Foundation/APIManager.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController.swift
Labels: 🤖 [Fix]

#370 [#369] 친구 추가 기능 동작 안하는 이슈 수정
  SobokSobok/SobokSobok/Service/Network/APIServices/Account/AddAccountService.swift
Labels: 🤖 [Fix]

#372 [#371] 친구 이름 수정 시 바로 반영되게 수정
  SobokSobok/SobokSobok/Data/DTO/APIModel/Share/Member.swift
  SobokSobok/SobokSobok/Presentation/Share/EditFriendName/EditFriendNameViewController.swift
  SobokSobok/SobokSobok/Presentation/Share/ShareViewController.swift
Labels: 🤖 [Fix], 🍀 태현

#375 [#359] 메인 -> 약수정 화면 전환
  SobokSobok/SobokSobok/Common/Extension/Notification+Extension.swift
  SobokSobok/SobokSobok/Presentation/Main/Cells/MainScheduleCell.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleDataSource.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Views/ScheduleHeaderView.swift
Labels: 🤖 [Fix], 🍀 승찬

#382 [#381] 로그인/회원가입 ~ 로그아웃/회원탈퇴 플로우 점검
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Common/Helper/UserDefaultsManager.swift
  SobokSobok/SobokSobok/Network/API/AccountEndPoint.swift
  SobokSobok/SobokSobok/Network/Service/AccountManager.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/Settings/SettingViewController.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/Settings/Withdraw/WithdrawCompleteViewController.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/Settings/Withdraw/WithdrawViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/Settings/Withdraw/WithdrawalViewController.swift
  SobokSobok/SobokSobok/Presentation/Share/ShareViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/SignIn/SocialSignInViewController.swift
  SobokSobok/SobokSobok/Presentation/SignUp/CompleteSignUpViewController.swift
  SobokSobok/SobokSobok/Presentation/Splash/SplashView.swift
Labels: 🤖 [Fix], 🍀 태현

#380 [#379] 약관 및 정책 링크 연결
  SobokSobok/SobokSobok/Presentation/MyInfo/Settings/Terms/TermsAndPolicesViewController.swift
  SobokSobok/SobokSobok/Presentation/SignUp/SetNickNameVIewController.swift
  SobokSobok/SobokSobok/Presentation/SignUp/SetNickNameVIewController.xib
Labels: 🤖 [Fix], 🍀 선영, ⚒ 내 정보
