Repository TeamSobokSobok/Sobok-iOS, pull requests merged in 2022-08, with the labels that each got.

#241 [#239] 공유 탭 API 연결
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Data/DTO/APIModel/Home/Pill.swift
  SobokSobok/SobokSobok/Network/API/ScheduleEndPoint.swift
  SobokSobok/SobokSobok/Network/Service/ScheduleManager.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController.swift
  SobokSobok/SobokSobok/Presentation/Share/ShareViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/Share/ShareViewController.swift
  SobokSobok/SobokSobok/Presentation/Share/Views/ShareTopView.swift
Labels: 🍀 태현, 🏀 공유 탭, 🌐 서버연결

#243 [#240] 스티커 관련 API 구현
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Data/DTO/APIModel/Sticker/Sticker.swift
  SobokSobok/SobokSobok/Network/API/StickerEndPoint.swift
  SobokSobok/SobokSobok/Network/Service/StickerManager.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController.swift
Labels: 🍀 태현, 🌐 서버연결

#247 [Feat] 약 개수 관련 API 연결 (#231)
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Data/DTO/APIModel/Medicine/PillCount.swift
  SobokSobok/SobokSobok/Network/API/PillCountEndPoint.swift
  SobokSobok/SobokSobok/Network/Service/PillCountlManager.swift
  SobokSobok/SobokSobok/Presentation/Pill/AddMedicineSheet/ViewControllers/AddMedicineSheet.swift
Labels: 🍀 승찬, 🌐 서버연결

#249 [Feat] 약 개수에 따른 화면 전환 처리 (#248)
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/Common/TabBarController.swift
  SobokSobok/SobokSobok/Presentation/Pill/AddPillSheet/Cell/AddPillTableViewCell.swift
  SobokSobok/SobokSobok/Presentation/Pill/AddPillSheet/Cell/AddPillTableViewCell.xib
  SobokSobok/SobokSobok/Presentation/Pill/AddPillSheet/ViewController/AddPillSheet.swift
  SobokSobok/SobokSobok/Presentation/Pill/AddPillSheet/ViewController/AddPillSheet.xib
  SobokSobok/SobokSobok/Presentation/Pill/AddPillSheet/ViewModel/AddPillSheetViewModel.swift
Labels: 📦 [Feat], 🍀 승찬

#251 [Feat] 다른 사람에게 약 전송 친구 리스트 구현 (#250)
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/AddUser/AddUserViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/SelectFriend/SelectFriendView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/SelectFriend/SelectFriendViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/SelectFriend/SelectFriendViewModel.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/Send/SendFillFirstViewController.swift
Labels: 📦 [Feat], 🍀 승찬

#253 [#245] 홈 탭 및 공유 탭 UI 데이터 연결
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/Common/BaseViewController.swift
  SobokSobok/SobokSobok/Presentation/Common/Sheet/StickerBottomSheet/StickerBottomSheet.swift
  SobokSobok/SobokSobok/Presentation/Common/TabBarController.swift
  SobokSobok/SobokSobok/Presentation/Main/Cells/MainScheduleCell.swift
  SobokSobok/SobokSobok/Presentation/Main/ViewControllers/MainViewController.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Cells/ScheduleCell.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController+DataSource.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController+FSCalendar.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Dictionary/PillColorType.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Dictionary/StickerType.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Views/ScheduleHeaderView.swift
  SobokSobok/SobokSobok/Presentation/Share/Cells/ShareScheduleCell.swift
  SobokSobok/SobokSobok/Presentation/Share/SendStickerPopUpViewController.swift
  SobokSobok/SobokSobok/Presentation/Share/ShareViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/Share/ShareViewController.swift
  SobokSobok/SobokSobok/Presentation/Share/Views/StateView.swift
  SobokSobok/SobokSobok/Resource/Image.xcassets/icEdit40.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/icEdit40.imageset/icEdit40.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/icEdit40.imageset/icEdit40@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/icEdit40.imageset/icEdit40@3x.png
Labels: 🍀 태현, 🚨 빠른리뷰필요, 🏚 홈 탭, 🏀 공유 탭, 🌐 서버연결

#255 [#254] ScheduleViewController DataSource 코드 개선
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/Main/ViewControllers/MainViewController.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleDataSource.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController+DataSource.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Views/ScheduleEmptyView.swift
  SobokSobok/SobokSobok/Presentation/Share/SendStickerPopUpViewController.swift
  SobokSobok/SobokSobok/Presentation/Share/ShareViewController.swift
Labels: 코드 개선

#257 [#202] 알림탭 관련 레이아웃과 API 연결
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Common/Extension/UIAlertController+Extension.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Notice/AcceptCalendarModel.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Notice/AcceptFriendModel.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Notice/AcceptPillModel.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Notice/NoticeListCountModel.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Notice/NoticeListModel.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Notice/PillDetailInfoModel.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Notice/PillMoreInfoModel.swift
  SobokSobok/SobokSobok/Network/API/NoticeEndPoint.swift
  SobokSobok/SobokSobok/Network/Service/NoticeManager.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Cells/FriendRequestCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/NoticeFirstControl.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/NoticeViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/NoticeViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/ViewControllers/NoticeViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/Cell/EmptyView.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/Cell/NoticeListCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/NoticeListView.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/NoticeSecondControl.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/PillInfoView.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/PillInfoViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/PillInfoViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/ViewControllers/Views/PillInfoViewController.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/Notice/NoticeAPI.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/Notice/NoticeService.swift
Labels: 🎨 [Style], 📦 [Feat], 🍀 은희, 🥚 알림 탭

#260 [#259] 참조 누락된 파일 추가
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/Cell/NoticeListCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/Cell/NoticeListSection.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/NoticeListView.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/PillInfoViewController.swift
Labels: 🤖 [Fix], 🍀 은희, 🚨 빠른리뷰필요

#263 [Feat] 약 추가 API 연결
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Common/Extension/String+Extension.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Medicine/SendPill.swift
  SobokSobok/SobokSobok/Network/API/SendPillEndPoint.swift
  SobokSobok/SobokSobok/Network/Service/SendPillManager.swift
  SobokSobok/SobokSobok/Presentation/Pill/AddPillSheet/ViewController/AddPillSheet.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPill/ViewController/AddPillFirstViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/PillLimit/View/PillLimitView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/PillLimit/ViewController/PillLimitViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillSecond/ViewController/AddPillSecondViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/ViewController/AddPillInfoViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/ViewController/AddPillThirdViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/Send/SendFillFirstViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/SendPillViewModel.swift
Labels: 📦 [Feat], 🍀 승찬

#262 [#256] Schedule Cell 코드 개선
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Application/SceneDelegate.swift
  SobokSobok/SobokSobok/Common/Extension/Date+Extension.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Medicine/AddPill.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Medicine/PillCount.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Pill/PillCount.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Pill/SendPill.swift
  SobokSobok/SobokSobok/Presentation/Main/Cells/MainScheduleCell.swift
  SobokSobok/SobokSobok/Presentation/Pill/AddPillSheet/ViewController/AddPillSheet.swift
  SobokSobok/SobokSobok/Presentation/Pill/AddPillSheet/ViewModel/AddPillSheetViewModel.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPill/ViewController/AddPillFirstViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/PillLimit/ViewController/PillLimitViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/Send/SendFillFirstViewController.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Cells/ScheduleCell.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleDataSource.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Views/ScheduleHeaderView.swift
  SobokSobok/SobokSobok/Presentation/Share/Cells/ShareScheduleCell.swift
Labels: 🍀 태현, 코드 개선

#266 [#246] 캘린더 커스텀
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Common/Extension/Date+Extension.swift
  SobokSobok/SobokSobok/Common/NameSpace/Image.swift
  SobokSobok/SobokSobok/Presentation/Common/Sample/SampleViewController.swift
  SobokSobok/SobokSobok/Presentation/Common/Sample/SampleViewController.xib
  SobokSobok/SobokSobok/Presentation/Common/Views/CalendarView.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Cells/CalendarDayCell.swift
  SobokSobok/SobokSobok/Resource/Image.xcassets/ic_setting_48_black.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/ic_setting_48_black.imageset/아이콘.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/ic_setting_48_black.imageset/아이콘@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/ic_setting_48_black.imageset/아이콘@3x.png
Labels: 🍀 태현, 🗓 캘린더

#267 [#258] 알림탭 관련 데이터 분기처리
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Common/Extension/Date+Extension.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Notice/AcceptPillModel.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Notice/NoticeListModel.swift
  SobokSobok/SobokSobok/Network/API/NoticeEndPoint.swift
  SobokSobok/SobokSobok/Network/Service/NoticeManager.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/NoticeViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/NoticeViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/Cell/EmptyView.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/Cell/NoticeListCollectionViewCell+Interaction.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/Cell/NoticeListCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/Cell/NoticeListSection.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/NoticeListView.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/PillInfoViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/PillInfoViewController.swift
Labels: 📦 [Feat], 🍀 은희, 🥚 알림 탭

#268 [Fix] PillThird CollectionView Fix (#264)
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Common/Extension/UITextField+Extension.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillSecond/ViewController/AddPillSecondViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/Cell/AddPillCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/View/AddPillFooterView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/View/AddPillThirdView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/ViewController/AddPillThirdViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/ViewController/Cell/AddPillCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/ViewController/Cell/PillTableViewCell.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/ViewController/Cell/TakePillTimeCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/ViewModel/PillThirdViewModel.swift
Labels: 🤖 [Fix], 🍀 승찬

#270 [#269] Conflicts 해결
  SobokSobok/SobokSobok/Common/Extension/Date+Extension.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/PillInfoViewController.swift
Labels: ✚ [Add], 🍀 은희, 🚨 빠른리뷰필요

#242 [Feat] 내정보 _ 회원 탈퇴 뷰 구현
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/MyInfo/Settings/SettingViewController.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/Settings/SettingViewController.xib
  SobokSobok/SobokSobok/Presentation/MyInfo/Settings/WithdrawalViewController.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/Settings/WithdrawalViewController.xib
Labels: 🎨 [Style], 📦 [Feat], 🍀 선영, ⚒ 내 정보

#275 [#271] 스티커 관련 연결 작업
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Common/Extension/UIStackView+Extension.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Home/Pill.swift
  SobokSobok/SobokSobok/Presentation/Common/Sheet/StickerCollectionViewCell.xib
  SobokSobok/SobokSobok/Presentation/Schedule/Cells/ScheduleCell.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleDataSource.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController.swift
Labels: 🍀 태현

#276 [#272] 약 추가 QA 1차 반영
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Common/Extension/UIImage+Extension.swift
  SobokSobok/SobokSobok/Common/Protocol/Protocol ++ .swift
  SobokSobok/SobokSobok/Presentation/Common/Views/NavigationView.swift
  SobokSobok/SobokSobok/Presentation/Common/Views/SpecificView.swift
  SobokSobok/SobokSobok/Presentation/Pill/AddPillSheet/ViewController/AddPillSheet.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPill/View/AddPillFirstView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPill/ViewController/AddPillFirstViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPill/ViewModel/PillTimeViewModel.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPillTime/View/AddPillFirstFooterView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPillTime/ViewModel/AddTimeViewModel.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/PillDay/View/PillDayView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/PillPeriod/View/PillPeriodView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillSecond/View/AddPillSecondView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillSecond/ViewController/AddPillSecondViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/ViewController/AddPillThirdViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/SelectFriend/SelectFriendViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/SelectFriend/SelectFriendViewModel.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/Send/SendFillFirstView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/Send/SendFillFirstViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/PillStyle.swift
Labels: 🤖 [Fix], 🍀 승찬

#278 [#273] 홈, 공유 디자인 QA 1차 반영
  SobokSobok/SobokSobok/Presentation/Common/TabBarController.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController+FSCalendar.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Views/ScheduleHeaderView.swift
Labels: 🍀 태현, 🏚 홈 탭, 🏀 공유 탭

#280 [#279] 닉네임 뷰, 이름 수정 뷰, 내 정보 뷰 화면 연결
  SobokSobok/SobokSobok/Presentation/Account/SearchNicknameViewController.xib
  SobokSobok/SobokSobok/Presentation/EditFriendName/EditFriendNameViewController.xib
  SobokSobok/SobokSobok/Presentation/Main/ViewControllers/MainViewController.swift
  SobokSobok/SobokSobok/Presentation/Main/Views/HomeTopView.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Views/FriendNameView.swift
  SobokSobok/SobokSobok/Presentation/Share/ShareViewController.swift
  SobokSobok/SobokSobok/Presentation/Share/Views/ShareTopView.swift
  SobokSobok/SobokSobok/Service/Network/APIServices/Account/AddAccountService.swift
Labels: 🍀 태현

#288 [#283] 약 추가 캘린더 UI 및 기능 수정
  SobokSobok/SobokSobok/Presentation/Common/Sample/SampleViewController.swift
  SobokSobok/SobokSobok/Presentation/Common/Views/CalendarView.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Cells/CalendarDayCell.swift
Labels: 🍀 태현, 🗓 캘린더

#289 [#285] 약 중단 UI 구현
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Network/Service/SendPillManager.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPill/ViewController/AddPillFirstViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/StopPillView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/StopPillViewController.swift
Labels: 🎨 [Style], 🍀 승찬

#295 [#294] UserDefaultsManager 생성 및 fcmToken 저장
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Application/AppDelegate.swift
  SobokSobok/SobokSobok/Common/Helper/UserDefaultsManager.swift
Labels: ⚙️ [Set], 🍀 태현

#296 [#274] NoticeSecond 연결
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Application/SceneDelegate.swift
  SobokSobok/SobokSobok/Common/Extension/String+Extension.swift
  SobokSobok/SobokSobok/Common/Extension/UIAlertController+Extension.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Notice/AcceptFriendModel.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Notice/AcceptPillModel.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Notice/NoticeListModel.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Notice/PillDetailInfoModel.swift
  SobokSobok/SobokSobok/Network/API/NoticeEndPoint.swift
  SobokSobok/SobokSobok/Network/Foundation/APIEnvironment.swift
  SobokSobok/SobokSobok/Network/Service/NoticeManager.swift
  SobokSobok/SobokSobok/Presentation/Common/Views/TimeView.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/NoticeFirstControl.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/NoticeViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/NoticeViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/Cell/NoticeListCollectionViewCell+Interaction.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/Cell/NoticeListCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/Cell/NoticeListSection.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/NoticeListView.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/NoticeToolTipView.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/PillInfoView.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/PillInfoViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/PillInfoViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/UserData/NoticeSingleton.swift
Labels: 🍀 은희, 🥚 알림 탭, 🌐 서버연결

#300 [#299] 스티커 기능 관련 수정
  SobokSobok/SobokSobok/Data/DTO/APIModel/Home/Pill.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Sticker/Sticker.swift
  SobokSobok/SobokSobok/Network/Foundation/APIManager.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Cells/ScheduleCell.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleDataSource.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController.swift
Labels: 🤖 [Fix], 🍀 태현

#302 [#297] 약 정보 상세보기 뷰 연결과 상세보기 데이터 전달
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/NoticeViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/Cell/NoticeListCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/Cell/NoticeListSection.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/PillInfoViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/PillInfoViewController.swift
Labels: 🎨 [Style], 🤖 [Fix], 🍀 은희, 🥚 알림 탭

#307 [#306] Custom ToolTip 추가 및 SceneDelegate 수정
  .gitignore
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Application/SceneDelegate.swift
  SobokSobok/SobokSobok/Presentation/Common/Views/SobokToolTipView.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/Cell/NoticeListCollectionViewCell.swift
Labels: 🎨 [Style], ⚙️ [Set], 🍀 은희

#309 [#305] 약 추가 플로우 디테일 수정
  SobokSobok/SobokSobok/Common/Helper/UserDefaultsManager.swift
  SobokSobok/SobokSobok/Common/Protocol/Protocol ++ .swift
  SobokSobok/SobokSobok/Presentation/Common/TabBarController.swift
  SobokSobok/SobokSobok/Presentation/Edit/ViewController/EditViewController.swift
  SobokSobok/SobokSobok/Presentation/Main/Cells/MainScheduleCell.swift
  SobokSobok/SobokSobok/Presentation/Pill/AddPillSheet/ViewController/AddPillSheet.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPill/View/ViewController/AddPillFirstViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillSecond/ViewController/AddPillSecondViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/ViewController/AddPillInfoViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/ViewController/AddPillThirdViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/NoFriend/ViewController/NoFriendViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/SelectFriend/SelectFriendView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/SelectFriend/SelectFriendViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/SelectFriend/SelectFriendViewModel.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/Send/SendFillFirstView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/Send/SendFillFirstViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/PillStyle.swift
  SobokSobok/SobokSobok/Presentation/Pill/SendPillViewModel.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController.swift
Labels: 🤖 [Fix], 🍀 승찬

#311 [#308] 메인 플로우 서버 호출 개선
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Common/Extension/Notification+Extension.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Cells/ScheduleCell.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController+FSCalendar.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Views/DynamicHeightCollectionView.swift
  SobokSobok/SobokSobok/Presentation/Share/SendStickerPopUpViewController.swift
Labels: 🤖 [Fix], 🍀 태현

#318 [#303] NoticeSecond 문제 해결 및 뷰 디자인 QA 반영, WIP
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Common/Extension/UIAlertController+Extension.swift
  SobokSobok/SobokSobok/Common/NameSpace/Image.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Notice/AcceptFriendModel.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Notice/AcceptPillModel.swift
  SobokSobok/SobokSobok/Network/API/NoticeEndPoint.swift
  SobokSobok/SobokSobok/Network/Service/NoticeManager.swift
  SobokSobok/SobokSobok/Presentation/Common/Views/TimeView.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/NoticeViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/NoticeViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/Cell/NoticeListCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/NoticeAlertController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/PillInfoViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/Views/PillInfoView.swift
  SobokSobok/SobokSobok/Presentation/Notice/Protocol/NoticeFirstControl.swift
  SobokSobok/SobokSobok/Presentation/Notice/Protocol/NoticeSecondControl.swift
  SobokSobok/SobokSobok/Presentation/Notice/UserData/NoticeSingleton.swift
  SobokSobok/SobokSobok/Resource/Image.xcassets/icDetail16.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/icDetail16.imageset/icDetail16.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/icDetail16.imageset/icDetail16@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/icDetail16.imageset/icDetail16@3x.png
Labels: 🤖 [Fix], 🍀 은희, 🥚 알림 탭

#320 [#316] 카카오 소셜 로그인 및 기타 구현
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SobokSobok/SobokSobok/Application/AppDelegate.swift
  SobokSobok/SobokSobok/Application/SceneDelegate.swift
  SobokSobok/SobokSobok/Common/Helper/UserDefaultsManager.swift
  SobokSobok/SobokSobok/Common/NameSpace/Image.swift
  SobokSobok/SobokSobok/Network/Foundation/APIEnvironment.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/PillLimit/ViewController/PillLimitViewController.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleDataSource.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController.swift
  SobokSobok/SobokSobok/Presentation/Share/ShareViewController.swift
  SobokSobok/SobokSobok/Presentation/Share/Views/ShareEmptyView.swift
  SobokSobok/SobokSobok/Presentation/SignIn/SocialSignInViewController.swift
  SobokSobok/SobokSobok/Presentation/SignUp/CompleteSignUpViewController.swift
  SobokSobok/SobokSobok/Presentation/Splash/SplashView.swift
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustAddFriend.imageset/Group 1348.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustAddFriend.imageset/Group 1348@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/illustAddFriend.imageset/Group 1348@3x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/new.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/new.imageset/Group 1348.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/new.imageset/Group 1348@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/new.imageset/Group 1348@3x.png
  SobokSobok/SobokSobok/Support/Info.plist
Labels: 🎨 [Style], 🍀 태현, 🌐 서버연결

#322 [#319] 알림 정보 전체보기 자잘한 이슈 해결
  SobokSobok/SobokSobok/Common/Extension/Notification+Extension.swift
  SobokSobok/SobokSobok/Network/API/NoticeEndPoint.swift
  SobokSobok/SobokSobok/Presentation/Common/Views/SobokToolTipView.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/NoticeViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/NoticeViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/Cell/NoticeListCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/NoticeAlertController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/PillInfoViewController.swift
Labels: 📦 [Feat], 🤖 [Fix], 🍀 은희, 🥚 알림 탭

#323 [#310] popRootViewController Fix
  SobokSobok/SobokSobok.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPill/View/ViewController/AddPillFirstViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillSecond/ViewController/AddPillSecondViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/ViewController/AddPillThirdViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/StopPillViewController.swift
Labels: 🤖 [Fix], 🍀 승찬

#326 [#325] 약 수정 API 연결
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Data/DTO/APIModel/Pill/SendPill.swift
  SobokSobok/SobokSobok/Network/API/PillEditEndPoint.swift
  SobokSobok/SobokSobok/Network/Service/PillEditManager.swift
  SobokSobok/SobokSobok/Presentation/Edit/ViewController/EditViewController.swift
  SobokSobok/SobokSobok/Presentation/Edit/ViewModel/EditCommonViewModel.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/View/FirstPillNameView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/ViewController/AddPillThirdViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/SendPillViewModel.swift
Labels: 📦 [Feat], 🍀 승찬

#328 [#292] 내 정보 뷰 서버 연결 및 화면 전환
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Common/Extension/String+Extension.swift
  SobokSobok/SobokSobok/Common/NameSpace/Image.swift
  SobokSobok/SobokSobok/Common/Protocol/Protocol ++ .swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Account/UserPillListModel.swift
  SobokSobok/SobokSobok/Network/API/AccountEndPoint.swift
  SobokSobok/SobokSobok/Network/Service/AccountManager.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/MyInfoTableViewCell.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/MyInfoTableViewCell.xib
  SobokSobok/SobokSobok/Presentation/MyInfo/MyInfoViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/MyInfoViewController.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/MyInfoViewController.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/PillInfoViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/ViewControllers/Views/PillInfoViewController.swift
Labels: 📦 [Feat], 🍀 은희, 🌐 서버연결, ⚒ 내 정보

#329 [#313] 약 삭제, 복약 중단 API 구현
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Data/DTO/APIModel/Home/EmptyData.swift
  SobokSobok/SobokSobok/Network/API/ScheduleEndPoint.swift
  SobokSobok/SobokSobok/Network/Foundation/APIManager.swift
  SobokSobok/SobokSobok/Network/Service/ScheduleManager.swift
Labels: 🍀 태현, 💊 스케줄

#331 [#330] 닉네임・친구 이름 수정 기능 연결
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Application/SceneDelegate.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Account/UserNickNameEditModel.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Notice/NoticeListModel.swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Share/EditFriendNicknameModel.swift
  SobokSobok/SobokSobok/Data/Model/EditFriendUsername.swift
  SobokSobok/SobokSobok/Data/Model/SaveNicknameModel.swift
  SobokSobok/SobokSobok/Data/Model/SearchNicknameModel.swift
  SobokSobok/SobokSobok/Network/API/AccountEndPoint.swift
  SobokSobok/SobokSobok/Network/Service/AccountManager.swift
  SobokSobok/SobokSobok/Presentation/EditFriendName/EditFriendNameViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/EditFriendName/EditFriendNameViewController.swift
  SobokSobok/SobokSobok/Presentation/EditFriendName/EditFriendNameViewController.xib
  SobokSobok/SobokSobok/Presentation/MyInfo/EditNickname/EditNicknameViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/EditNickname/EditNicknameViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/NoticeViewController.swift
Labels: 📦 [Feat], 🍀 은희, 🌐 서버연결

#332 [#327] 약 이름 UI 수정
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPill/View/ViewController/AddPillFirstViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/View/AddPillFooterView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/View/AddPillThirdView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/View/PillNameViewCell.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/ViewController/AddPillThirdViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/ViewModel/PillThirdViewModel.swift
Labels: 🤖 [Fix], 🍀 승찬

#334 [#321] 회원가입 ~ 메인, 공유 ~ 친구 추가 플로우 점검
  SobokSobok/SobokSobok/Application/SceneDelegate.swift
  SobokSobok/SobokSobok/Common/Helper/UserDefaultsManager.swift
  SobokSobok/SobokSobok/Network/Foundation/APIEnvironment.swift
  SobokSobok/SobokSobok/Presentation/Account/SaveNicknameViewController.swift
  SobokSobok/SobokSobok/Presentation/Main/ViewControllers/MainViewController.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController.swift
  SobokSobok/SobokSobok/Presentation/Share/ShareViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/Share/ShareViewController.swift
  SobokSobok/SobokSobok/Presentation/SignIn/SocialSignInViewController.swift
  SobokSobok/SobokSobok/Presentation/SignUp/SetNickNameVIewController.swift
Labels: 🤖 [Fix]

#335 [#333] 약 수정 API 연결 및 약 수정 UI Fix
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Common/Protocol/Protocol ++ .swift
  SobokSobok/SobokSobok/Data/DTO/APIModel/Account/UserPillListModel.swift
  SobokSobok/SobokSobok/Network/API/AccountEndPoint.swift
  SobokSobok/SobokSobok/Network/Service/AccountManager.swift
  SobokSobok/SobokSobok/Presentation/Edit/View/EditPillDateView.swift
  SobokSobok/SobokSobok/Presentation/Edit/View/EditView.swift
  SobokSobok/SobokSobok/Presentation/Edit/ViewController/EditViewController.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/MyInfoTableViewCell.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/MyInfoViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/MyInfoViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/View/PillNameViewCell.swift
Labels: 🤖 [Fix], 🍀 승찬, 🌐 서버연결

#338 [#337] 내 정보 뷰 기능 수정
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/Edit/ViewController/EditViewController.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/MyInfoPillCell.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/MyInfoTableViewCell.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/MyInfoTableViewCell.xib
  SobokSobok/SobokSobok/Presentation/MyInfo/MyInfoViewController.swift
  SobokSobok/SobokSobok/Presentation/MyInfo/MyInfoViewController.xib
  SobokSobok/SobokSobok/Resource/Image.xcassets/ic_setting_48_black.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/ic_setting_48_black.imageset/ic_setting_48_black.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/ic_setting_48_black.imageset/ic_setting_48_black@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/ic_setting_48_black.imageset/ic_setting_48_black@3x.png
Labels: 🍀 태현, 💊 스케줄

#339 [#336] 약 이름 Fix Index Error
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillSecond/ViewController/AddPillSecondViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/ViewController/AddPillThirdViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/ViewController/Cell/PillNameViewCell.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/SelectFriend/SelectFriendViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/SendPillViewModel.swift
Labels: 🤖 [Fix], 🍀 승찬

#343 [#340] 약 추가 플로우 수정
  SobokSobok/SobokSobok/Data/DTO/APIModel/Notice/NoticeListModel.swift
  SobokSobok/SobokSobok/Network/Foundation/APIEnvironment.swift
  SobokSobok/SobokSobok/Presentation/Common/TabBarController.swift
  SobokSobok/SobokSobok/Presentation/Edit/ViewController/EditViewController.swift
  SobokSobok/SobokSobok/Presentation/Main/Cells/MainScheduleCell.swift
  SobokSobok/SobokSobok/Presentation/Pill/AddPillSheet/ViewController/AddPillSheet.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPill/View/ViewController/AddPillFirstViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPill/ViewModel/PillTimeViewModel.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPillTime/ViewModel/AddTimeViewModel.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillSecond/ViewController/AddPillSecondViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/View/AddPillInfoView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/View/AddPillThirdView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/View/PillPeriodTimeView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/ViewController/AddPillInfoViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/ViewController/AddPillThirdViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/NoFriend/ViewController/NoFriendViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/Send/SendFillFirstViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/SendPillViewModel.swift
Labels: 🤖 [Fix], 🍀 승찬

#346 [#345] 토큰 수정 및 빌드 번호 수정
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Network/Foundation/APIEnvironment.swift
Labels: 🤖 [Fix], 🍀 태현
