Repository TeamSobokSobok/Sobok-iOS, pull requests merged in 2022-05, with the labels that each got.

#187 [#184] 약 정보 상세보기 뷰 UI 구현
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Common/NameSpace/Image.swift
  SobokSobok/SobokSobok/Data/Model/SendInfoDataModel.swift
  SobokSobok/SobokSobok/Data/Model/SendInfoListDataModel.swift
  SobokSobok/SobokSobok/Presentation/Common/Views/NavigationBarView.swift
  SobokSobok/SobokSobok/Presentation/Common/Views/TimeView.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/Cells/PillInfoCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/ViewControllers/PillInfoViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/Views/PillInfoFooterView.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/Views/PillInfoHeaderView.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/Views/PillInfoView.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThird/Cells/PillTimeInfoCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThird/Cells/PillTimeInfoCollectionViewCell.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThird/Cells/WeekSelectTableViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThird/Cells/WeekSelectTableViewCell.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThird/ViewControllers/PillInfoEditViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThird/ViewControllers/PillInfoEditViewController.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThird/ViewControllers/TermSelectViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThird/ViewControllers/TermSelectViewController.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThird/ViewControllers/WeekSelectViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThird/ViewControllers/WeekSelectViewController.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeThird/Views/PillTimeInfoFooterView.swift
  SobokSobok/SobokSobok/Resource/Image.xcassets/ic_more_16_black.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/ic_more_16_black.imageset/ic_more_16_black.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/ic_more_16_black.imageset/ic_more_16_black@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/ic_more_16_black.imageset/ic_more_16_black@3x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/ic_pill_alarm_22_darkmint.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/ic_pill_alarm_22_darkmint.imageset/ic_pill_alarm_22_darkmint.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/ic_pill_alarm_22_darkmint.imageset/ic_pill_alarm_22_darkmint@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/ic_pill_alarm_22_darkmint.imageset/ic_pill_alarm_22_darkmint@3x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/ic_share_alarm_22_darkmint.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/ic_share_alarm_22_darkmint.imageset/ic_share_alarm_22_darkmint.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/ic_share_alarm_22_darkmint.imageset/ic_share_alarm_22_darkmint@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/ic_share_alarm_22_darkmint.imageset/ic_share_alarm_22_darkmint@3x.png
Labels: 🎨 [Style], 📦 [Feat], 🍀 은희

#191 [Add] ScheduleViewController.swift
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/Schedule/ScheduleViewController.swift
Labels: ✚ [Add], 🍀 태현

#192 [Style] 약 추가 3 UI 구현
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SobokSobok/SobokSobok/Common/Extension/UICollectionView + Extension.swift
  SobokSobok/SobokSobok/Common/NameSpace/Image.swift
  SobokSobok/SobokSobok/Presentation/Pill/PillFirst/ViewController/AddPillFirstViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/PillSecond/View/AddPillSecondView.swift
  SobokSobok/SobokSobok/Presentation/Pill/PillThird/Cell/AddPillCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Pill/PillThird/Cell/PillTableViewCell.swift
  SobokSobok/SobokSobok/Presentation/Pill/PillThird/Cell/TakePillTimeCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Pill/PillThird/View/AddPillFooterView.swift
  SobokSobok/SobokSobok/Presentation/Pill/PillThird/View/AddPillInfoView.swift
  SobokSobok/SobokSobok/Presentation/Pill/PillThird/View/AddPillThirdView.swift
  SobokSobok/SobokSobok/Presentation/Pill/PillThird/View/LeftAlignedCollectionViewFlowLayout.swift
  SobokSobok/SobokSobok/Presentation/Pill/PillThird/View/PillNameView.swift
  SobokSobok/SobokSobok/Presentation/Pill/PillThird/View/PillPeriodTimeView.swift
  SobokSobok/SobokSobok/Presentation/Pill/PillThird/ViewController/AddPillInfoViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/PillThird/ViewController/AddPillThirdViewController.swift
  SobokSobok/SobokSobok/Resource/Image.xcassets/icInfo.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/icInfo.imageset/icInfo.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/icInfo.imageset/icInfo@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/icInfo.imageset/icInfo@3x.png
Labels: 🎨 [Style], 🍀 승찬
