Repository TeamSobokSobok/Sobok-iOS, pull requests merged in 2022-11, with the labels that each got.

#384 [#376] 약추가, 약수정 QA 반영
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/Edit/View/EditPillNameView.swift
  SobokSobok/SobokSobok/Presentation/Edit/View/EditView.swift
  SobokSobok/SobokSobok/Presentation/Edit/ViewController/EditViewController.swift
  SobokSobok/SobokSobok/Presentation/Main/Cells/MainScheduleCell.swift
  SobokSobok/SobokSobok/Presentation/Pill/AddPillSheet/ViewController/AddPillSheet.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/AddSuccessFriendView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/AddSuccessFriendViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/AddSuccessView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/AddSuccessViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/PillDay/View/PillDayView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/View/AddPillThirdView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/ViewController/AddPillInfoViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/ViewController/AddPillThirdViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/PillStyle.swift
Labels: 🤖 [Fix], 🍀 승찬

#385 [#383] 공유 엠티뷰 변경
  SobokSobok/SobokSobok/Presentation/Share/ShareViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/Share/Views/ShareEmptyView.swift
  SobokSobok/SobokSobok/Resource/Image.xcassets/new.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/new.imageset/Group 1348.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/new.imageset/Group 1348@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/new.imageset/Group 1348@3x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/new.imageset/_shareEmptyView.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/new.imageset/_shareEmptyView@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/new.imageset/_shareEmptyView@3x.png
Labels: 🏀 공유 탭

#386 [#357] 기능 QA 반영
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/Cells/NoticeListCollectionViewCell.swift
Labels: 🤖 [Fix], 🍀 은희, 🥚 알림 탭

#389 [#387] 약 추가 및 약 수정 QA 반영
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/Cell/NoticeListCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/AddSuccessView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPill/View/ViewController/AddPillFirstViewController.swift
Labels: 🤖 [Fix], 🍀 승찬
