Repository TeamSobokSobok/Sobok-iOS, pull requests merged in 2022-06, with the labels that each got.

#197 [#196] 다른 사람에게 약 전송 친구 없을 때 UI 구현
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Application/SceneDelegate.swift
  SobokSobok/SobokSobok/Common/NameSpace/Image.swift
  SobokSobok/SobokSobok/Presentation/Common/BaseViewController.swift
  SobokSobok/SobokSobok/Presentation/Common/Views/NavigationView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPill/View/AddPillFirstView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPill/ViewController/AddPillFirstViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPill/ViewModel/AddPillFirstViewModel.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPill/ViewModel/PillTimeViewModel.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPillTime/Cell/PillTimeCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPillTime/View/AddPillFirstFooterView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPillTime/View/AddPillTimeView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPillTime/ViewController/AddTimeViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/AddPillTime/ViewModel/AddTimeViewModel.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/FillLimit/ViewControllers/PillLimitViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/FillLimit/Views/PillLimitView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/PillDay/Cell/PillDayTableViewCell.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/PillDay/View/PillDayView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/PillDay/ViewController/PillDayViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/PillDay/ViewModel/PillDayViewModel.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/PillModel.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/PillPeriod/View/PillPeriodView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/PillPeriod/ViewController/PillPeriodViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillFirst/PillPeriod/ViewModel/PillPeriodViewModel.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillSecond/View/AddPillSecondView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillSecond/ViewController/AddPillSecondViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/Cell/AddPillCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/Cell/PillTableViewCell.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/Cell/TakePillTimeCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/View/AddPillFooterView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/View/AddPillInfoView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/View/AddPillThirdView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/View/LeftAlignedCollectionViewFlowLayout.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/View/PillNameView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/View/PillPeriodTimeView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/ViewController/AddPillInfoViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Me/PillThird/ViewController/AddPillThirdViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/NoFriend/View/NoFriendView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/NoFriend/ViewController/NoFriendViewController.swift
  SobokSobok/SobokSobok/Resource/Image.xcassets/icNoFriend.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/icNoFriend.imageset/icNoFriend.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/icNoFriend.imageset/icNoFriend@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/icNoFriend.imageset/icNoFriend@3x.png
Labels: 🎨 [Style], 🍀 승찬

#201 [#188] 알림 목록 뷰 UI 구현
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Common/Extension/Adjusted+Extension.swift
  SobokSobok/SobokSobok/Presentation/Common/BaseViewController.swift
  SobokSobok/SobokSobok/Presentation/Common/Views/NavigationBarView.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Cells/FriendRequestCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Cells/NoticeListCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Cells/PillRequestCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/ViewControllers/NoticeViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/NoticeListView.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/ViewControllers/PillInfoViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/Views/PillInfoView.swift
Labels: 🎨 [Style], 🍀 은희, 🥚 알림 탭

#205 [#198] 친구추가 UI 구현
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Application/SceneDelegate.swift
  SobokSobok/SobokSobok/Common/NameSpace/Image.swift
  SobokSobok/SobokSobok/Presentation/Common/Views/NavigationView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/AddUser/AddUserView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/AddUser/AddUserViewController.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/Share/SendPillFirstView.swift
  SobokSobok/SobokSobok/Presentation/Pill/Other/PillFirst/Share/SendPillFirstViewController.swift
  SobokSobok/SobokSobok/Resource/Image.xcassets/icMoreBlack48.imageset/Contents.json
  SobokSobok/SobokSobok/Resource/Image.xcassets/icMoreBlack48.imageset/icMoreBlack48.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/icMoreBlack48.imageset/icMoreBlack48@2x.png
  SobokSobok/SobokSobok/Resource/Image.xcassets/icMoreBlack48.imageset/icMoreBlack48@3x.png
Labels: 🎨 [Style], 🍀 승찬

#207 [#200] Network Layer Foundation
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Network/Foundation/APIError.swift
  SobokSobok/SobokSobok/Network/Foundation/APIManager.swift
  SobokSobok/SobokSobok/Network/Foundation/BaseModel.swift
  SobokSobok/SobokSobok/Network/Foundation/HttpMethod.swift
  SobokSobok/SobokSobok/Network/Foundation/NetworkRequest.swift
Labels: ⚙️ [Set], 🍀 태현

#209 [#208] HomeViewController(=MainVC) 리팩토링
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  SobokSobok/SobokSobok/Common/Extension/Encodable+Extension.swift
  SobokSobok/SobokSobok/Network/API/ScheduleEndPoint.swift
  SobokSobok/SobokSobok/Network/Foundation/APIEnvironment.swift
  SobokSobok/SobokSobok/Network/Foundation/EndPoint.swift
  SobokSobok/SobokSobok/Network/Service/ScheduleManager.swift
  SobokSobok/SobokSobok/Presentation/Common/TabBarController.swift
  SobokSobok/SobokSobok/Presentation/Home/HomeViewController.swift
  SobokSobok/SobokSobok/Presentation/Home/HomeViewController.xib
  SobokSobok/SobokSobok/Presentation/Main/.gitkeep
  SobokSobok/SobokSobok/Presentation/Main/ViewControllers/MainViewController+Network.swift
  SobokSobok/SobokSobok/Presentation/Main/ViewControllers/MainViewController.swift
  SobokSobok/SobokSobok/Presentation/Main/Views/HomeTopView.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Cells/ScheduleCell.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController+DataSource.swift
  SobokSobok/SobokSobok/Presentation/Schedule/Controllers/ScheduleViewController.swift
Labels: 🍀 태현, 🏚 홈 탭
