Repository TeamSobokSobok/Sobok-iOS, pull requests merged in 2022-03, with the labels that each got.

#177 [#175] Notice Second 뷰 UI 수정과 코드 정리
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/Common/Extension/UIAlertController+Extension.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Cells/NoticeListCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/ViewControllers/NoticeViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeFirst/Views/NoticeListView.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/Cells/FooterCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/Cells/FooterCollectionViewCell.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/Cells/PillInfoCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/Cells/SendInfoCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/Cells/SendInfoCollectionViewCell.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/Cells/SenderInfoCollectionViewCell.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/Cells/SenderInfoCollectionViewCell.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/ViewControllers/PillInfoViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/ViewControllers/SendInfoViewController.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/ViewControllers/SendInfoViewController.xib
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/Views/PillInfoFooterView.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/Views/PillInfoHeaderView.swift
  SobokSobok/SobokSobok/Presentation/Notice/NoticeSecond/Views/PillInfoView.swift
Labels: 🎨 [Style], 📦 [Feat], 🍀 은희, 🥚 알림 탭

#180 [Add] 프로젝트 APNs Capability 세팅(#171)
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
  SobokSobok/SobokSobok/SobokSobok.entitlements
  SobokSobok/SobokSobok/Support/Info.plist
Labels: ✚ [Add], 🍀 태현

#182 [Set] Provisioning Profile 등록
  SobokSobok/SobokSobok.xcodeproj/project.pbxproj
Labels: ⚙️ [Set]
